# ndarray.ndarray

In [8]:
import numpy as np

num = [1, 2, 4, 5]

a = np.array(num)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[1 2 4 5]
1
(4,)
4
int64


In [9]:
scalar = 1
scalar 

1

In [10]:
lst = [1,4,5,6]
 
vector = np.array(lst)
vector

array([1, 4, 5, 6])

In [11]:
vector.ndim

1

In [12]:
vector.shape

(4,)

In [13]:
vector.size

4

In [14]:
vector.dtype

dtype('int64')

In [17]:
rg = np.random.default_rng(1)

In [29]:
np.floor(10* rg.random((2,2)))

array([[6., 8.],
       [5., 2.]])