In [69]:
import numpy as np

lst = [1, 2, 3, 4, 5]
int_arr = np.array(lst, int)

int_arr

array([1, 2, 3, 4, 5])

In [70]:
import numpy as np

lst = [1, 2, '3', '4', "123"]
arr = np.array(lst, float)

arr

array([  1.,   2.,   3.,   4., 123.])

In [74]:
type(lst[4])

str

In [72]:
arr[4].dtype

dtype('float64')

In [75]:
import numpy as np

lst = [1, 2, '3', '4', "123"]
arr = np.array(lst, str)

arr

array(['1', '2', '3', '4', '123'], dtype='<U3')

In [76]:
import numpy as np

lst = [1, 2, '3', '4', "123"]
arr = np.array(lst, bool)

arr

array([ True,  True,  True,  True,  True])

In [85]:
import numpy as np

lst = [[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]]]
arr = np.array(lst)

arr.ndim

3

In [91]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr.shape

(2, 5)

In [92]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr.size

10

In [93]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr.dtype

dtype('int64')

In [94]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr.itemsize

8

In [95]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [96]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [97]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [98]:
np.iinfo(np.int16).min

-32768

In [99]:
np.iinfo(np.int16).max

32767

In [100]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [101]:
np.iinfo(np.int32).min

-2147483648

In [102]:
np.iinfo(np.int32).max

2147483647

In [103]:
np.iinfo(np.int32(10))

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [104]:
np.iinfo(np.int32(10)).min

-2147483648

In [105]:
np.iinfo(np.int32(10)).max

2147483647

In [106]:
np.iinfo(np.int32(10)).bits

32

In [108]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [115]:
np.finfo(np.float64).min

-1.7976931348623157e+308

In [116]:
np.finfo(np.float64).max

1.7976931348623157e+308

In [117]:
np.finfo(np.float64).maxexp

1024

In [118]:
np.finfo(np.float64).minexp

-1022

In [126]:
np.finfo(np.float64).tiny

2.2250738585072014e-308

In [127]:
np.power(100, 100, dtype=np.float64) # correct

1e+200

In [128]:
np.power(100, 100, dtype=np.int64) # incorrect

0

In [203]:
import numpy as np

np.random.seed(100)

np.random.randint(0, 10, 3)

array([8, 8, 3])

In [226]:
np.random.seed(1)

print(np.random.randint(0, 10, 3))

np.random.seed(2)

print(np.random.randint(0, 10, 3))

[5 8 9]
[8 8 6]


In [232]:
rg = np.random.default_rng(1)
np.floor(10* rg.random((2,2)))

array([[5., 9.],
       [1., 9.]])

In [293]:
rg = np.random.default_rng()
for r in rg.random((2, 2)):
    print(r)

[0.45109922 0.30266025]
[0.91705569 0.07620506]


In [296]:
rg = np.random.default_rng(42)
for r in rg.random((2, 2)):
    print(r)

[0.77395605 0.43887844]
[0.85859792 0.69736803]


In [265]:
import pandas as pd
import numpy as np

data = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame( data ,index=['one','two'], columns=['co1','col2','col3'])

# df.to_excel("/Users/jaynam/Desktop/test.xlsx")
df

co1  col2  col3
one    1     2     3
two    4     5     6

In [258]:
%pip install xlsxwriter

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 3.6 MB/s eta 0:00:00a 0:00:01
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Note: you may need to restart the kernel to use updated packages.


In [299]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr.base is None

True

In [303]:
import numpy as np

lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
arr = np.array(lst)

arr2 = arr[:,2]

arr2.base is arr

True